In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('data.csv')
data

   id     name   age gender      class  score
0   1    Alice  17.0      F       Math   88.0
1   2      Bob  18.0      M       Math   92.0
2   3  Charlie   NaN      M    Physics   85.0
3   4     Dana  17.0      F       Math    NaN
4   5      Eli  18.0      M    Physics   79.0
5   6    Farah  17.0      F  Chemistry   90.0

#  Filtering

<h3> Logical operators

In [5]:
# student older than 17
print(data [data['age']> 17] )

   id name   age gender    class  score
1   2  Bob  18.0      M     Math   92.0
4   5  Eli  18.0      M  Physics   79.0

In [9]:
# girls with score > 85
# USE ( ) to sepereate between each condition !!!!!!!!!!
print(data[ (data['gender']=='F') & (data['score']> 85) ])

   id   name   age gender      class  score
0   1  Alice  17.0      F       Math   88.0
5   6  Farah  17.0      F  Chemistry   90.0

<h3>Using .filter()

<h4> dataframe.filter(items, like, regex, axis)

In [25]:
print(data.filter(items=["name","age"]))

      name   age
0    Alice  17.0
1      Bob  18.0
2  Charlie  17.4
3     Dana  17.0
4      Eli  18.0
5    Farah  17.0

<h3> Using isin()

In [27]:
names = ['John','Catlin','Mike', 'Alice']
print(data[data.name.isin(names)])

   id   name   age gender class  score
0   1  Alice  17.0      F  Math   88.0

# Using str accessor

In [30]:
data[data.name.str.startswith('D')]

   id  name   age gender class  score
3   4  Dana  17.0      F  Math    0.0

In [33]:
data[data.name.str.contains('a')]

   id     name   age gender      class  score
2   3  Charlie  17.4      M    Physics   85.0
3   4     Dana  17.0      F       Math    0.0
5   6    Farah  17.0      F  Chemistry   90.0

# Using ~ (not )

In [36]:
data[~data.name.str.contains('o')]

   id     name   age gender      class  score
0   1    Alice  17.0      F       Math   88.0
2   3  Charlie  17.4      M    Physics   85.0
3   4     Dana  17.0      F       Math    0.0
4   5      Eli  18.0      M    Physics   79.0
5   6    Farah  17.0      F  Chemistry   90.0

## Using query

In [38]:
data.query('  age > 16 and   gender == "F" ')

   id   name   age gender      class  score
0   1  Alice  17.0      F       Math   88.0
3   4   Dana  17.0      F       Math    0.0
5   6  Farah  17.0      F  Chemistry   90.0

## Using loc and iloc

In [1]:
import pandas as pd
data = pd.read_csv('data.csv')
data.head()

   id     name   age gender    class  score
0   1    Alice  17.0      F     Math   88.0
1   2      Bob  18.0      M     Math   92.0
2   3  Charlie   NaN      M  Physics   85.0
3   4     Dana  17.0      F     Math    NaN
4   5      Eli  18.0      M  Physics   79.0

- Loc: Select rows or columns using labels


- Iloc: Select rows or columns using indices

In [5]:
data.iloc[3:5, :] # rows 3 and 4 all columns

   id  name   age gender    class  score
3   4  Dana  17.0      F     Math    NaN
4   5   Eli  18.0      M  Physics   79.0

In [6]:
data.loc[3:5, :] # rows 3 and 4 all columns

   id   name   age gender      class  score
3   4   Dana  17.0      F       Math    NaN
4   5    Eli  18.0      M    Physics   79.0
5   6  Farah  17.0      F  Chemistry   90.0

We can see the same results.

Let's change the index for bette runderstanding

In [7]:
data

   id     name   age gender      class  score
0   1    Alice  17.0      F       Math   88.0
1   2      Bob  18.0      M       Math   92.0
2   3  Charlie   NaN      M    Physics   85.0
3   4     Dana  17.0      F       Math    NaN
4   5      Eli  18.0      M    Physics   79.0
5   6    Farah  17.0      F  Chemistry   90.0

In [8]:
data.index= ["a", "b", "c", "d", "e", "f"]
data

   id     name   age gender      class  score
a   1    Alice  17.0      F       Math   88.0
b   2      Bob  18.0      M       Math   92.0
c   3  Charlie   NaN      M    Physics   85.0
d   4     Dana  17.0      F       Math    NaN
e   5      Eli  18.0      M    Physics   79.0
f   6    Farah  17.0      F  Chemistry   90.0

In [9]:
data.loc['b': 'd', :]

   id     name   age gender    class  score
b   2      Bob  18.0      M     Math   92.0
c   3  Charlie   NaN      M  Physics   85.0
d   4     Dana  17.0      F     Math    NaN

In [ ]:
#data.iloc['b': 'd', :] # ---> error

TypeError: cannot do positional indexing on Index with these indexers [b] of type str

# Grouping

In [11]:
# average score by class

# we group by class # Then for each class we calculate the mean of scores
print(data.groupby("class")["score"].mean())

class
Chemistry    90.0
Math         90.0
Physics      82.0
Name: score, dtype: float64

In [12]:
# # Max score by gender

print(data.groupby("gender")["score"].max())

gender
F    90.0
M    92.0
Name: score, dtype: float64

# Handling missing values

In [13]:
data.isnull().sum()

id        0
name      0
age       1
gender    0
class     0
score     1
dtype: int64

In [14]:
# # Fill missing ages with the mean

data["age"].fillna(data["age"].mean(), inplace= True)

In [15]:
# # Fill missing scores with 0

data["score"].fillna(0, inplace= True)

In [16]:
data.isnull().sum()

id        0
name      0
age       0
gender    0
class     0
score     0
dtype: int64

# Merging

In [17]:
#  Create a second table with ID and email
df_emails = pd.DataFrame({
    "id": [1, 2, 3, 4, 5, 6],
    "email": ["a@x.com", "b@x.com", "c@x.com", "d@x.com", "e@x.com", "f@x.com"]
})

In [18]:
df_emails

   id    email
0   1  a@x.com
1   2  b@x.com
2   3  c@x.com
3   4  d@x.com
4   5  e@x.com
5   6  f@x.com

In [20]:
data

   id     name   age gender      class  score
0   1    Alice  17.0      F       Math   88.0
1   2      Bob  18.0      M       Math   92.0
2   3  Charlie  17.4      M    Physics   85.0
3   4     Dana  17.0      F       Math    0.0
4   5      Eli  18.0      M    Physics   79.0
5   6    Farah  17.0      F  Chemistry   90.0

In [24]:
# merging based on id

data_merged= data.merge(df_emails, on="id")
data_merged

   id     name   age gender      class  score    email
0   1    Alice  17.0      F       Math   88.0  a@x.com
1   2      Bob  18.0      M       Math   92.0  b@x.com
2   3  Charlie  17.4      M    Physics   85.0  c@x.com
3   4     Dana  17.0      F       Math    0.0  d@x.com
4   5      Eli  18.0      M    Physics   79.0  e@x.com
5   6    Farah  17.0      F  Chemistry   90.0  f@x.com

In [22]:
merged = pd.merge(data, df_emails, on="id")
print(merged.head())

   id     name   age gender    class  score    email
0   1    Alice  17.0      F     Math   88.0  a@x.com
1   2      Bob  18.0      M     Math   92.0  b@x.com
2   3  Charlie  17.4      M  Physics   85.0  c@x.com
3   4     Dana  17.0      F     Math    0.0  d@x.com
4   5      Eli  18.0      M  Physics   79.0  e@x.com