<h1><center> Features preprocessing

# 1)- Label Encoder / One Hot Encoder

In [23]:
import pandas as pd 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [24]:
data = pd.DataFrame({
    "couleur": ['rouge', 'vert', 'bleu', 'orange'],
    "taille": ['petit', 'grand', 'moyen', 'petit']
})
data

  couleur taille
0   rouge  petit
1    vert  grand
2    bleu  moyen
3  orange  petit

In [25]:
# label encoder pour les variables ordinales
le = LabelEncoder()
data['taille_le'] = le.fit_transform(data['taille'])


data

  couleur taille  taille_le
0   rouge  petit          2
1    vert  grand          0
2    bleu  moyen          1
3  orange  petit          2

In [26]:
# one hot encoder pour les variables nominales


ohe = OneHotEncoder(sparse_output=False)  
encoded = ohe.fit_transform(data[["couleur"]])

# Convertir en DataFrame
encoded_df = pd.DataFrame(encoded, columns=ohe.get_feature_names_out(["couleur"]))

# Concaténer avec dataset
data_final = pd.concat([data, encoded_df], axis=1)


data_final

  couleur taille  taille_le  ...  couleur_orange  couleur_rouge  couleur_vert
0   rouge  petit          2  ...             0.0            1.0           0.0
1    vert  grand          0  ...             0.0            0.0           1.0
2    bleu  moyen          1  ...             0.0            0.0           0.0
3  orange  petit          2  ...             1.0            0.0           0.0

[4 rows x 7 columns]

In [39]:
# appliquer sur titanic dataset

import seaborn as sns

titanic= sns.load_dataset('titanic')
titanic.dropna(inplace=True)
titanic.drop_duplicates(inplace=True)
# pour faciliter
titanic.drop(columns=['who','pclass','adult_male', 'deck', 'sibsp',	'parch'	,'fare'	,'embarked', 'alone', 'alive'], inplace=True)
titanic.head()

    survived     sex   age  class  embark_town
1          1  female  38.0  First    Cherbourg
3          1  female  35.0  First  Southampton
6          0    male  54.0  First  Southampton
10         1  female   4.0  Third  Southampton
11         1  female  58.0  First  Southampton

In [43]:
# label encoder to class

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
titanic['class_le'] = le.fit_transform(titanic['class'])
titanic.head()

    survived     sex   age  class  embark_town  class_le
1          1  female  38.0  First    Cherbourg         0
3          1  female  35.0  First  Southampton         0
6          0    male  54.0  First  Southampton         0
10         1  female   4.0  Third  Southampton         2
11         1  female  58.0  First  Southampton         0

In [44]:
# one hot encoder pour les colonnes sex et cherboug
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output= False)
encoded = ohe.fit_transform(titanic[['sex', 'embark_town']])
encoded_df = pd.DataFrame(encoded, columns= ohe.get_feature_names_out(['sex', 'embark_town']))
data_final = pd.concat([titanic, encoded_df], axis=1)

data_final.head()

    survived     sex  ...  embark_town_Queenstown embark_town_Southampton
1        1.0  female  ...                     0.0                     1.0
3        1.0  female  ...                     0.0                     1.0
6        0.0    male  ...                     0.0                     1.0
10       1.0  female  ...                     0.0                     1.0
11       1.0  female  ...                     0.0                     1.0

[5 rows x 11 columns]

## Différence entre label encoder et ordinal encoder

In [46]:
data= pd.DataFrame({"taille": ['first', 'second', 'third', 'fourth']})

le = LabelEncoder()
data['taille_le']= le.fit_transform(data['taille'])

data # suit l'ordre alphabétique

   taille  taille_le
0   first          0
1  second          2
2   third          3
3  fourth          1

In [49]:
from sklearn.preprocessing import OrdinalEncoder

data= pd.DataFrame({"taille": ['first', 'second', 'third', 'fourth']})

oe = OrdinalEncoder(categories=[['first', 'second', 'third','fourth']])
data['taille_oe'] = oe.fit_transform(data[['taille']])
data

   taille  taille_oe
0   first        0.0
1  second        1.0
2   third        2.0
3  fourth        3.0