<h1><center>Jour 16 – Handling Missing, Duplicate, and Noisy Data

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
titanic = sns.load_dataset('titanic')
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [3]:
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [4]:
titanic.notnull().sum()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [5]:
data_droped_null_columns = titanic.dropna(axis=1)
data_droped_null_columns

,survived,pclass,sex,sibsp,parch,fare,class,who,adult_male,alive,alone
0,0,3,male,1,0,7.2500,Third,man,True,no,False
1,1,1,female,1,0,71.2833,First,woman,False,yes,False
2,1,3,female,0,0,7.9250,Third,woman,False,yes,True
3,1,1,female,1,0,53.1000,First,woman,False,yes,False
4,0,3,male,0,0,8.0500,Third,man,True,no,True
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,0,0,13.0000,Second,man,True,no,True
887,1,1,female,0,0,30.0000,First,woman,False,yes,True
888,0,3,female,1,2,23.4500,Third,woman,False,no,False
889,1,1,male,0,0,30.0000,First,man,True,yes,True
890,0,3,male,0,0,7.7500,Third,man,True,no,True

In [6]:
data_droped_null_values = titanic.dropna()
data_droped_null_values

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
872,0,1,male,33.0,0,0,5.0000,S,First,man,True,B,Southampton,no,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [7]:
data_droped_null_values.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [8]:
titanic.duplicated().sum()

107

In [9]:
titanic.drop_duplicates(inplace=True)
titanic.duplicated().sum()

0

In [21]:
# au lieu de supprimer les valeurs nulles, on les remplaces par mean, median, mode, ffill, bfill

data = sns.load_dataset('titanic')

data['age_mean'] = data['age'].fillna(data['age'].mean())
data['age_median'] = data['age'].fillna(data['age'].median())
data['age_mode'] = data['age'].fillna(data['age'].mode()[0])
data['age_ffill'] = data['age'].fillna(method="ffill")
data['age_bfill'] = data['age'].fillna(method="bfill")

print(data.iloc[888])  # one of the null values for age

survived                 0
pclass                   3
sex                 female
age                    NaN
sibsp                    1
parch                    2
fare                 23.45
embarked                 S
class                Third
who                  woman
adult_male           False
deck                   NaN
embark_town    Southampton
alive                   no
alone                False
age_mean         29.699118
age_median            28.0
age_mode              24.0
age_ffill             19.0
age_bfill             26.0
Name: 888, dtype: object

In [32]:
# gestion des valeurs bruitées


# Majuscule/Miniscule
df= pd.DataFrame({
    'sex' : ['male  ', "    Male", "MALE", "MaLe"]
})
print(df)

        sex
0    male
1      Male
2      MALE
3      MaLe

In [34]:
df['sex']= df['sex'].str.lower()
print(df)

        sex
0    male
1      male
2      male
3      male

In [ ]:
df['sex']= df['sex'].str.strip() # supprime les espaces
print(df)

    sex
0  male
1  male
2  male
3  male

In [ ]:
# fautes de frappes

df= pd.DataFrame({
    'city': ['Paris', 'Pariss', 'pari']
})
print(df)

     city
0   Paris
1  Pariss
2    pari

In [37]:
df['city']= df['city'].replace({
    "pari": "Paris", 
    "Pariss": "Paris"})

print(df)

    city
0  Paris
1  Paris
2  Paris

In [38]:
# valuers numériques non logiques
# age= -5 age= 2000

df = pd.DataFrame({
                        "age": [1, 12, 23, -5, 2000, 20, 36]
})

print(df)

    age
0     1
1    12
2    23
3    -5
4  2000
5    20
6    36

In [39]:
df['age'] = df['age'].apply(lambda x: x if 0<= x <= 120 else np.nan)

print(df)

    age
0   1.0
1  12.0
2  23.0
3   NaN
4   NaN
5  20.0
6  36.0

In [44]:
# datetime formatée
df = pd.DataFrame({
                    "Date": ["2025-09-19", "19/09/25", "Sept 19 2025"]
})

print(df)

           Date
0    2025-09-19
1      19/09/25
2  Sept 19 2025

In [46]:
df['Date'] = pd.to_datetime(df['Date'], errors="coerce")
print(df)
#Cela veut dire : si pandas n’arrive pas à convertir une valeur en date valide, il met NaT (Not a Time) au lieu de planter une erreur.

        Date
0 2025-09-19
1 2025-09-19
2 2025-09-19

In [47]:
# datetime formatée
df = pd.DataFrame({
                    "Date": ["hhhhh", "19/09/25", "Sept 19 2025"]
})

print(df)

df['Date'] = pd.to_datetime(df['Date'], errors="raise")
print(df)

           Date
0         hhhhh
1      19/09/25
2  Sept 19 2025

ParserError: Unknown string format: hhhhh present at position 0

In [48]:
df = pd.DataFrame({
                    "Date": ["hhhhh", "19/09/25", "Sept 19 2025"]
})

print(df)

df['Date'] = pd.to_datetime(df['Date'], errors="coerce")
print(df)

           Date
0         hhhhh
1      19/09/25
2  Sept 19 2025
        Date
0        NaT
1 2025-09-19
2 2025-09-19