<h1><center> Projet 2: Beijing PM2.5 </center></h1>

In [38]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [39]:
df = pd.read_csv("data.csv")
df.head()

   No  year  month  day  hour  pm2.5  DEWP  TEMP    PRES cbwd    Iws  Is  Ir
0   1  2010      1    1     0    NaN   -21 -11.0  1021.0   NW   1.79   0   0
1   2  2010      1    1     1    NaN   -21 -12.0  1020.0   NW   4.92   0   0
2   3  2010      1    1     2    NaN   -21 -11.0  1019.0   NW   6.71   0   0
3   4  2010      1    1     3    NaN   -21 -14.0  1019.0   NW   9.84   0   0
4   5  2010      1    1     4    NaN   -20 -12.0  1018.0   NW  12.97   0   0

In [40]:
df.tail()

,No,year,month,day,hour,pm2.5,DEWP,TEMP,PRES,cbwd,Iws,Is,Ir
43819,43820,2014,12,31,19,8.0,-23,-2.0,1034.0,NW,231.97,0,0
43820,43821,2014,12,31,20,10.0,-22,-3.0,1034.0,NW,237.78,0,0
43821,43822,2014,12,31,21,10.0,-22,-3.0,1034.0,NW,242.70,0,0
43822,43823,2014,12,31,22,8.0,-22,-4.0,1034.0,NW,246.72,0,0
43823,43824,2014,12,31,23,12.0,-21,-3.0,1034.0,NW,249.85,0,0

In [41]:
df.shape

(43824, 13)

In [42]:
# 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43824 entries, 0 to 43823
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   No      43824 non-null  int64
 1   year    43824 non-null  int64
 2   month   43824 non-null  int64
 3   day     43824 non-null  int64
 4   hour    43824 non-null  int64
 5   pm2.5   41757 non-null  float64
 6   DEWP    43824 non-null  int64
 7   TEMP    43824 non-null  float64
 8   PRES    43824 non-null  float64
 9   cbwd    43824 non-null  object
 10  Iws     43824 non-null  float64
 11  Is      43824 non-null  int64
 12  Ir      43824 non-null  int64
dtypes: float64(4), int64(8), object(1)
memory usage: 4.3+ MB

In [43]:
df.describe()

,No,year,month,day,hour,pm2.5,DEWP,TEMP,PRES,Iws,Is,Ir
count,43824.000000,43824.000000,43824.000000,43824.000000,43824.000000,41757.000000,43824.000000,43824.000000,43824.000000,43824.000000,43824.000000,43824.000000
mean,21912.500000,2012.000000,6.523549,15.727820,11.500000,98.613215,1.817246,12.448521,1016.447654,23.889140,0.052734,0.194916
std,12651.043435,1.413842,3.448572,8.799425,6.922266,92.050387,14.433440,12.198613,10.268698,50.010635,0.760375,1.415867
min,1.000000,2010.000000,1.000000,1.000000,0.000000,0.000000,-40.000000,-19.000000,991.000000,0.450000,0.000000,0.000000
25%,10956.750000,2011.000000,4.000000,8.000000,5.750000,29.000000,-10.000000,2.000000,1008.000000,1.790000,0.000000,0.000000
50%,21912.500000,2012.000000,7.000000,16.000000,11.500000,72.000000,2.000000,14.000000,1016.000000,5.370000,0.000000,0.000000
75%,32868.250000,2013.000000,10.000000,23.000000,17.250000,137.000000,15.000000,23.000000,1025.000000,21.910000,0.000000,0.000000
max,43824.000000,2014.000000,12.000000,31.000000,23.000000,994.000000,28.000000,42.000000,1046.000000,585.600000,27.000000,36.000000

In [44]:
df.isnull().sum()

No          0
year        0
month       0
day         0
hour        0
pm2.5    2067
DEWP        0
TEMP        0
PRES        0
cbwd        0
Iws         0
Is          0
Ir          0
dtype: int64

In [45]:
df.duplicated().sum()

0

## 1. Explorer les données

In [46]:
# Colonne 1: 'year'
print(f"Le valeur de la colonne year sont : {df['year'].unique()}")

Le valeur de la colonne year sont : [2010 2011 2012 2013 2014]

In [47]:
df['year'].value_counts()

year
2012    8784
2010    8760
2011    8760
2013    8760
2014    8760
Name: count, dtype: int64

In [48]:
# Colone 2: 'month'

print(f"Les valeurs de la colonne month sont: {df['month'].unique()}")

Les valeurs de la colonne month sont: [ 1  2  3  4  5  6  7  8  9 10 11 12]

In [49]:
df["month"].value_counts()

month
1     3720
3     3720
5     3720
7     3720
8     3720
10    3720
12    3720
4     3600
6     3600
9     3600
11    3600
2     3384
Name: count, dtype: int64

In [50]:
# Colonne 3: 'day' 
print(f"Les valeurs de la colonne day sont: {df['day'].unique()}")

Les valeurs de la colonne day sont: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31]

In [51]:
df["day"].value_counts().sort_index()

day
1     1440
2     1440
3     1440
4     1440
5     1440
6     1440
7     1440
8     1440
9     1440
10    1440
11    1440
12    1440
13    1440
14    1440
15    1440
16    1440
17    1440
18    1440
19    1440
20    1440
21    1440
22    1440
23    1440
24    1440
25    1440
26    1440
27    1440
28    1440
29    1344
30    1320
31     840
Name: count, dtype: int64

In [52]:
# Colonne 4: 'hour' 
print(f"Les valeurs de la colonne hour sont: {df['hour'].unique()}")

Les valeurs de la colonne hour sont: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

In [53]:
# Colonne 5: 'pm2.5' 
df['pm2.5'].isna().sum()

2067

In [54]:
df = df.dropna()
print(df['pm2.5'].isna().sum())

0

In [55]:
# Colonne 6: 'Dew point'
print(f"Les valeurs de la colonne dew point sont: {df['DEWP'].unique()}")

Les valeurs de la colonne dew point sont: [-16 -15 -11  -7  -8  -9 -10 -12 -14 -17 -18 -19 -20 -21 -22 -23 -24 -26
 -27 -25 -13  -5  -6  -4  -3  -2  -1   0   2   3   1   5   6   7   4   8
   9  10  11  13  15  16  17  18  14  12  19  20  21  22  23  24  25  26
  27  28 -28 -29 -31 -30 -32 -33 -35 -34 -36 -37 -39 -40 -38]

Le point de rosée est la température à laquelle l'air doit être refroidi, à pression constante, pour que la vapeur d'eau qu'il contient se transforme en eau liquide (condensation).
-  Un point de rosée inférieur à 15 °C (50-60 °F) est confortable.
-  Entre 16 °C et 18 °C, l'air commence à paraître lourd ou humide.
-  Au-dessus de 20 °C, l'atmosphère devient très lourde et moite

In [56]:
# Colonne 7: 'Temperature'
print(f"Les valeurs de la colonne Temperature sont: {df['TEMP'].unique()}")

Les valeurs de la colonne Temperature sont: [ -4.          -5.          -6.          -7.          -8.
  -9.         -10.         -11.         -12.         -13.
 -15.         -17.         -18.         -19.         -16.
 -14.          -3.          -2.          -1.           0.
   1.           2.           3.           4.           6.
   8.           7.           5.           9.          10.
  11.          12.          13.          14.          15.
  16.          17.          19.          20.          21.
  22.          18.          23.          24.          25.
  28.          31.          32.          29.          27.
  26.          30.          33.          34.          35.
  36.          37.          38.          39.          40.
  41.          42.          14.66666667   9.33333333]

In [57]:
# On garde juste deux chiffres après la virgule
df['TEMP'] = round(df['TEMP'], 2)
print(f"Alors ces valeurs sont devenues : {df['TEMP'].unique()}")

Alors ces valeurs sont devenues : [ -4.    -5.    -6.    -7.    -8.    -9.   -10.   -11.   -12.   -13.
 -15.   -17.   -18.   -19.   -16.   -14.    -3.    -2.    -1.     0.
   1.     2.     3.     4.     6.     8.     7.     5.     9.    10.
  11.    12.    13.    14.    15.    16.    17.    19.    20.    21.
  22.    18.    23.    24.    25.    28.    31.    32.    29.    27.
  26.    30.    33.    34.    35.    36.    37.    38.    39.    40.
  41.    42.    14.67   9.33]

In [58]:
# Colonne 8: 'Pression'  
print(f"Les valeurs de la colonne Pression sont: {df['PRES'].unique()}")

Les valeurs de la colonne Pression sont: [1020.       1021.       1022.       1023.       1024.       1025.
 1026.       1027.       1028.       1029.       1030.       1031.
 1032.       1033.       1034.       1035.       1036.       1037.
 1038.       1039.       1019.       1018.       1017.       1016.
 1015.       1014.       1013.       1012.       1011.       1010.
 1009.       1008.       1007.       1006.       1004.       1003.
 1002.       1005.       1040.       1041.       1042.       1001.
 1000.        999.        997.        996.        998.        995.
  994.       1043.       1019.5      1029.666667 1032.333333 1044.
 1045.        993.        992.       1046.       1027.5       991.      ]

In [59]:
# On garde juste deux chiffres après la virgule
df['PRES'] = round(df['PRES'], 2)
print(f"Alors ces valeurs sont devenues : {df['PRES'].unique()}")

Alors ces valeurs sont devenues : [1020.   1021.   1022.   1023.   1024.   1025.   1026.   1027.   1028.
 1029.   1030.   1031.   1032.   1033.   1034.   1035.   1036.   1037.
 1038.   1039.   1019.   1018.   1017.   1016.   1015.   1014.   1013.
 1012.   1011.   1010.   1009.   1008.   1007.   1006.   1004.   1003.
 1002.   1005.   1040.   1041.   1042.   1001.   1000.    999.    997.
  996.    998.    995.    994.   1043.   1019.5  1029.67 1032.33 1044.
 1045.    993.    992.   1046.   1027.5   991.  ]

In [ ]:
# Colonne 9: 'Combined wind direction'
print(f"Les valeurs de la colonne 'cbwd' sont: {df['cbwd'].unique()}")

Les valeurs de la colonne 'cbwd' sont: ['SE' 'cv' 'NW' 'NE']

In [64]:
# On remplace 'cv' par 'CV'
df['cbwd'] = df['cbwd'].replace("cv", "CV")
print(f"Les valeurs de la colonne 'cbwd' sont: {df['cbwd'].unique()}")

Les valeurs de la colonne 'cbwd' sont: ['SE' 'CV' 'NW' 'NE']

In [65]:
# On définit un dictionnaire des paires clés-valeurs de la colonne 'cbwd' 

cbwd_dict = {
    "SE" : "South-East",
    "NW" : "North-West",
    "NE" : "North-East",
    "CV" : "Calm and Variable"
}

In [66]:
df['cbwd'].value_counts()

cbwd
SE    14573
NW    13484
CV     8944
NE     4756
Name: count, dtype: int64

In [73]:
# Colonne 10: 'Cumulated wind speed'
print(f"Les valeurs de la colonne 'Iws' sont: {df['Iws'].unique()}.\nIl existe {len(df['Iws'].unique())} valeurs différentes.")

Les valeurs de la colonne 'Iws' sont: [  1.79   2.68   3.57 ... 242.7  246.72 249.85].
Il existe 2723 valeurs différentes.

In [75]:
# Colonne 11: 'Cumulated hours of snow'
print(f"Les valeurs de la colonne 'Is' sont: {df['Is'].unique()}")

Les valeurs de la colonne 'Is' sont: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 15 16 17 19 20 21 22 23 24 25
 26 27 14 18]

In [77]:
# Colonne 12: 'Cumulated hours of rain'
print(f"Les valeurs de la colonne 'Ir' sont: {df['Ir'].unique()}.")

Les valeurs de la colonne 'Ir' sont: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36].

<hr>

## 2. Visualisation des données